### ISSUE TITLE
Fails on WSL

### ISSUE THREAD

**Issue by queil** [arciisine/vscode-chronicler#17]
Hey, I've been running VS Code in Windows Subsystem for Linux (WSL2). When I start recording I get: 
```
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at parseJSON (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/node_modules/@arcsine/win-info/index.js:9:21)
	at Object.getActive (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/node_modules/@arcsine/win-info/index.js:46:16)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async Function.getWindow (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/node_modules/@arcsine/screen-recorder/lib/os.js:38:22)
	at async Function.recordActiveWindow (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/node_modules/@arcsine/screen-recorder/lib/recorder.js:7:42)
	at async Recorder.run (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/out/recorder.js:52:21)
	at async record (/home/user/.vscode-server/extensions/arcsine.chronicler-0.1.7/out/extension.js:52:25)
``` 

Is this scenario supported or even possible?

**Comment by arciisine** [comment]
The actual error is in the @arcsine/win-info package which is used for
getting window location and dimensions.

I'm not familiar enough with wsl to know what window manager it uses. I'll
need to research that

**Comment by arciisine** [comment]
Looking at https://www.reddit.com/r/linuxquestions/comments/8b5zaz/xrandr_on_wsl/, it looks like `xrarndr` may not be properly supported.  You can look at https://github.com/arciisine/win-info/blob/master/native/x11/main.ts for more details.  

I'll need to look further to see if anyone has solved this issue.

**Comment by Lv777F** [comment]
I have resolved this question by specifying vscode-chronicler run in windows not wsl;
1. Edit setting.json
``` json
{
  "remote.extensionKind" : {
    "arcsine.chronicler" : ["ui"]
  }
}
```
2. Open a empty project in windows;
3. Run chronicler and install ffmpeg in windows path;
4. Open your project in wsl and it's working fine.

**Comment by arciisine** [comment]
That's awesome.  I can update the readme to include this is you are cool
with that.

**Comment by Trass3r** [comment]
@arciisine actually this can be fixed in the package.json.
See https://github.com/sirmspencer/vscode-autohide/pull/10/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R14

**Comment by TorstenIhben** [comment]
Hi @arciisine!

I have the same issue when using VS Code on Windows with Remote Development with SSH. Also for this case the workaround suggested by @Trass3r works fine!
