### ISSUE TITLE
Command failed (can't record)

### ISSUE THREAD

**Issue by heitor-lassarote** [arciisine/vscode-chronicler#29]
# Problem

Running Chronicler is failing with the following error:

```
Command failed: /opt/visual-studio-code/code /home/heitor/.vscode/extensions/arcsine.chronicler-0.1.14/node_modules/@arcsine/win-info/bin/win-info-x11.js active
```

Additionally, in `Log (Extension Host)`, I see the following output, which I'm not sure whether it's related:

```
[2021-11-16 09:25:31.618] [exthost] [error] Error: info:No recording running
    at Recorder.stop (/home/heitor/.vscode/extensions/arcsine.chronicler-0.1.14/out/recorder.js:66:19)
    at Recorder.dispose (/home/heitor/.vscode/extensions/arcsine.chronicler-0.1.14/out/recorder.js:14:14)
    at h (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:4961)
    at w._deactivate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11584)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9997
    at Array.map (<anonymous>)
    at w.deactivateAll (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9985)
    at b.terminate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:735)
    at o (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:32681)
    at Socket.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30296)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```

# Environment
OS: Arch Linux
ffmpeg version: n4.4.1
X.org version: 1.21.1.1
VS Code version: 1.62.2

**Comment by arciisine** [comment]
Are you able to run a few debugging commands:
`npx @arcsine/win-info` and `npx @arcsine/screen-recorder test.mp4`? The output from these commands should help pinpoint where the issue is.

**Comment by heitor-lassarote** [comment]
Here is the output for `npx @arcsine/win-info`:
```
{
  "title": "CantusFirmus.hs - fux - Visual Studio Code",
  "id": 73400321,
  "owner": {
    "name": "Code",
    "processId": 2388
  },
  "screens": [
    {
      "index": 1,
      "width": 1920,
      "height": 1080,
      "x": 0,
      "y": 0,
      "scale": {
        "x": 1,
        "y": 1
      }
    }
  ],
  "bounds": {
    "x": 64,
    "y": 21,
    "width": 1856,
    "height": 1059
  }
}
```
Here's the output for `npx @arcsine/screen-recorder test.mp4`:
```
/usr/bin/ffmpeg -threads 4 -video_size 1856x1060 -f x11grab -i :1+64,20 -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[x11grab @ 0x55e750cf2300] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':1+64,20':
  Duration: N/A, start: 1637186839.175532, bitrate: 1886778 kb/s
Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1856x1060, 1886778 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0x55e750d06c40] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x55e750cfd840] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55e750cfd840] profile High 4:4:4 Predictive, level 4.0, 4:4:4, 8-bit
[libx264 @ 0x55e750cfd840] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=6 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf58.76.100
Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj444p(pc, progressive), 1856x1060, q=2-31, 29.97 fps, 30k tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A
frame=   20 fps=0.0 q=0.0 size=       0kB time=00:00:00.20 bitrate=   1.9kbits/s dup=10 drop=0 speed=0.391x
frame=   36 fps= 35 q=0.0 size=       0kB time=00:00:00.73 bitrate=   0.5kbits/s dup=10 drop=8 speed=0.711x
frame=   51 fps= 33 q=0.0 size=       0kB time=00:00:01.23 bitrate=   0.3kbits/s dup=10 drop=8 speed=0.804x
frame=   67 fps= 32 q=0.0 size=       0kB time=00:00:01.76 bitrate=   0.2kbits/s dup=10 drop=8 speed=0.855x
frame=   82 fps= 32 q=0.0 size=       0kB time=00:00:02.26 bitrate=   0.2kbits/s dup=10 drop=8 speed=0.883x
frame=   97 fps= 32 q=0.0 size=       0kB time=00:00:02.76 bitrate=   0.1kbits/s dup=10 drop=8 speed=0.901x
Done
frame=  111 fps= 31 q=-1.0 Lsize=      12kB time=00:00:03.67 bitrate=  27.1kbits/s dup=10 drop=8 speed=1.02x    
video:11kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.541566%
[libx264 @ 0x55e750cfd840] frame I:1     Avg QP: 7.00  size:  7087
[libx264 @ 0x55e750cfd840] frame P:110   Avg QP: 0.02  size:    31
[libx264 @ 0x55e750cfd840] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x55e750cfd840] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:100.0%
[libx264 @ 0x55e750cfd840] coded y,u,v intra: 0.1% 0.1% 0.0% inter: 0.0% 0.0% 0.0%
[libx264 @ 0x55e750cfd840] i16 v,h,dc,p: 98%  0%  1%  0%
[libx264 @ 0x55e750cfd840] kb/s:22.79
Successfully terminated
```
I attach `test.mp4` here:

https://user-images.githubusercontent.com/30162364/142290389-c0949610-ed7e-447e-8a1a-8c430715040b.mp4

n.b.: I'm trying this out with Wayland now.

**Comment by arciisine** [comment]
So Wayland isn't currently supported because of it's inability to enumerate
the application windows (by design afaik).

**Comment by heitor-lassarote** [comment]
Here are the the outputs to these commands, but this time using X:

`npx @arcsine/win-info`:
```
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: xprop -root      $0 _NET_ACTIVE_WINDOW
xprop:  unable to open display ':1'

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xprop -root \t$0 _NET_ACTIVE_WINDOW',
  stdout: '',
  stderr: "xprop:  unable to open display ':1'\n"
}
node:child_process:867
    throw err;
    ^

Error: Command failed: /usr/bin/node /home/heitor/.npm/_npx/7bdea5cc73c9c05d/node_modules/@arcsine/win-info/bin/win-info-x11.js active
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: xprop -root      $0 _NET_ACTIVE_WINDOW
xprop:  unable to open display ':1'

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xprop -root \t$0 _NET_ACTIVE_WINDOW',
  stdout: '',
  stderr: "xprop:  unable to open display ':1'\n"
}

    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at getActiveSync (/home/heitor/.npm/_npx/7bdea5cc73c9c05d/node_modules/@arcsine/win-info/index.js:55:41)
    at Object.<anonymous> (/home/heitor/.npm/_npx/7bdea5cc73c9c05d/node_modules/@arcsine/win-info/bin/win-info.js:8:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    'node:child_process:397\n' +
      "      ex = new Error('Command failed: ' + cmd + '\\n' + stderr);\n" +
      '           ^\n' +
      '\n' +
      'Error: Command failed: xprop -root \t$0 _NET_ACTIVE_WINDOW\n' +
      "xprop:  unable to open display ':1'\n" +
      '\n' +
      '    at ChildProcess.exithandler (node:child_process:397:12)\n' +
      '    at ChildProcess.emit (node:events:390:28)\n' +
      '    at maybeClose (node:internal/child_process:1064:16)\n' +
      '    at Socket.<anonymous> (node:internal/child_process:450:11)\n' +
      '    at Socket.emit (node:events:390:28)\n' +
      '    at Pipe.<anonymous> (node:net:672:12) {\n' +
      '  killed: false,\n' +
      '  code: 1,\n' +
      '  signal: null,\n' +
      "  cmd: 'xprop -root \\t$0 _NET_ACTIVE_WINDOW',\n" +
      "  stdout: '',\n" +
      `  stderr: "xprop:  unable to open display ':1'\\n"\n` +
      '}\n'
  ],
  pid: 8416,
  stdout: '',
  stderr: 'node:child_process:397\n' +
    "      ex = new Error('Command failed: ' + cmd + '\\n' + stderr);\n" +
    '           ^\n' +
    '\n' +
    'Error: Command failed: xprop -root \t$0 _NET_ACTIVE_WINDOW\n' +
    "xprop:  unable to open display ':1'\n" +
    '\n' +
    '    at ChildProcess.exithandler (node:child_process:397:12)\n' +
    '    at ChildProcess.emit (node:events:390:28)\n' +
    '    at maybeClose (node:internal/child_process:1064:16)\n' +
    '    at Socket.<anonymous> (node:internal/child_process:450:11)\n' +
    '    at Socket.emit (node:events:390:28)\n' +
    '    at Pipe.<anonymous> (node:net:672:12) {\n' +
    '  killed: false,\n' +
    '  code: 1,\n' +
    '  signal: null,\n' +
    "  cmd: 'xprop -root \\t$0 _NET_ACTIVE_WINDOW',\n" +
    "  stdout: '',\n" +
    `  stderr: "xprop:  unable to open display ':1'\\n"\n` +
    '}\n'
}
```

`npx @arcsine/screen-recorder test.mp4`:
```
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: /usr/bin/node /home/heitor/.npm/_npx/c71e018737289961/node_modules/@arcsine/win-info/bin/win-info-x11.js active
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: xprop -root      $0 _NET_ACTIVE_WINDOW
xprop:  unable to open display ':1'

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xprop -root \t$0 _NET_ACTIVE_WINDOW',
  stdout: '',
  stderr: "xprop:  unable to open display ':1'\n"
}

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /home/heitor/.npm/_npx/c71e018737289961/node_modules/@arcsine/win-info/bin/win-info-x11.js active',
  stdout: '',
  stderr: 'node:child_process:397\n' +
    "      ex = new Error('Command failed: ' + cmd + '\\n' + stderr);\n" +
    '           ^\n' +
    '\n' +
    'Error: Command failed: xprop -root \t$0 _NET_ACTIVE_WINDOW\n' +
    "xprop:  unable to open display ':1'\n" +
    '\n' +
    '    at ChildProcess.exithandler (node:child_process:397:12)\n' +
    '    at ChildProcess.emit (node:events:390:28)\n' +
    '    at maybeClose (node:internal/child_process:1064:16)\n' +
    '    at Socket.<anonymous> (node:internal/child_process:450:11)\n' +
    '    at Socket.emit (node:events:390:28)\n' +
    '    at Pipe.<anonymous> (node:net:672:12) {\n' +
    '  killed: false,\n' +
    '  code: 1,\n' +
    '  signal: null,\n' +
    "  cmd: 'xprop -root \\t$0 _NET_ACTIVE_WINDOW',\n" +
    "  stdout: '',\n" +
    `  stderr: "xprop:  unable to open display ':1'\\n"\n` +
    '}\n'
}
```

Actually, the second time I tried running these commands, the output changed:
```
{
  "title": "CantusFirmus.hs - fux - Visual Studio Code",
  "id": 90177537,
  "owner": {
    "name": "Code",
    "processId": 9272
  },
  "screens": [
    {
      "index": 4,
      "width": 1920,
      "height": 1080,
      "x": 0,
      "y": 0,
      "scale": {
        "x": 1,
        "y": 1
      }
    }
  ],
  "bounds": {
    "x": 64,
    "y": 21,
    "width": 1856,
    "height": 1059
  }
}
```

```
/usr/bin/ffmpeg -threads 4 -video_size 1856x1060 -f x11grab -i :0+64,20 -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[x11grab @ 0x55d0d1e84300] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0+64,20':
  Duration: N/A, start: 1637194733.352115, bitrate: 1886778 kb/s
Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1856x1060, 1886778 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0x55d0d1e993c0] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x55d0d1e8ffc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55d0d1e8ffc0] profile High 4:4:4 Predictive, level 4.0, 4:4:4, 8-bit
[libx264 @ 0x55d0d1e8ffc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=6 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf58.76.100
Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj444p(pc, progressive), 1856x1060, q=2-31, 29.97 fps, 30k tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A
frame=   17 fps=0.0 q=0.0 size=     256kB time=00:00:00.10 bitrate=20947.5kbits/s dup=6 drop=0 speed=0.196x
frame=   34 fps= 34 q=0.0 size=     768kB time=00:00:00.66 bitrate=9427.9kbits/s dup=6 drop=4 speed=0.66x
frame=   49 fps= 32 q=0.0 size=     768kB time=00:00:01.16 bitrate=5387.5kbits/s dup=6 drop=4 speed=0.771x
frame=   64 fps= 32 q=0.0 size=    1024kB time=00:00:01.66 bitrate=5028.3kbits/s dup=6 drop=4 speed=0.827x
frame=   80 fps= 31 q=0.0 size=    1024kB time=00:00:02.20 bitrate=3809.3kbits/s dup=6 drop=4 speed=0.864x
frame=   96 fps= 31 q=1.0 size=    1024kB time=00:00:02.73 bitrate=3066.0kbits/s dup=6 drop=4 speed=0.89x
frame=  111 fps= 31 q=0.0 size=    1024kB time=00:00:03.23 bitrate=2591.9kbits/s dup=6 drop=4 speed=0.905x
frame=  127 fps= 31 q=0.0 size=    1280kB time=00:00:03.77 bitrate=2781.1kbits/s dup=6 drop=4 speed=0.918x
frame=  142 fps= 31 q=0.0 size=    1280kB time=00:00:04.27 bitrate=2455.2kbits/s dup=6 drop=4 speed=0.926x
Done
frame=  146 fps= 30 q=-1.0 Lsize=    1541kB time=00:00:04.83 bitrate=2609.4kbits/s dup=6 drop=4 speed=1.01x    
video:1540kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.091522%
[libx264 @ 0x55d0d1e8ffc0] frame I:1     Avg QP: 7.00  size:409526
[libx264 @ 0x55d0d1e8ffc0] frame P:145   Avg QP: 1.85  size:  8045
[libx264 @ 0x55d0d1e8ffc0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x55d0d1e8ffc0] mb P  I16..4:  0.5%  0.0%  0.0%  P16..4:  6.4%  0.0%  0.0%  0.0%  0.0%    skip:93.1%
[libx264 @ 0x55d0d1e8ffc0] coded y,u,v intra: 18.0% 9.0% 8.3% inter: 2.1% 0.4% 0.3%
[libx264 @ 0x55d0d1e8ffc0] i16 v,h,dc,p: 81% 18%  1%  0%
[libx264 @ 0x55d0d1e8ffc0] kb/s:2588.22
Successfully terminated
```

https://user-images.githubusercontent.com/30162364/142305770-419b42cd-c5b2-4d9c-8559-cfb139671ce8.mp4

So this time the command worked and recorded, but the extension still fails.

**Comment by arciisine** [comment]
So, for the win-info on X11, I'm seeing the error in your output:
```
  stderr: "xprop:  unable to open display ':1'\n"
```

The program should be inferring the display host from the environment variable.  Can you run:
```
echo $DISPLAY
```
And provide the output.

**Comment by heitor-lassarote** [comment]
The output again varies (first set of outputs or second set of outputs) before and after restarting the VS Code terminal, but the first time (with error) was `:0` and the second time (with success) was `:1`. Running it in non-VSC terminal always yields `:1`. I'm not sure if it helps, but I'm on a dual-monitor setup.

Just to make things simpler to debug, from now on I'll try on the ordinary terminal or on the restarted VSC terminal, so we have a more consistent set of outputs.

**Comment by arciisine** [comment]
Thanks for the info.  So, the display host, unless you are running a funky X11 setup should stay constant.  The fact that you see it moving between :1 and :0 is a little odd.  I just double checked the code, and its just consuming the DISPLAY env variable to know which display host to target. 

Since you moved back to X11, have you been able to try using the extension again?  If the terminal can successfully get win-info and record, the plugin is just calling those same pieces of functionality.

**Comment by ltshb** [comment]
I've a similar issue, were the chronicler fails as in above description. However running both following command `npx @arcsine/win-info` and `npx @arcsine/screen-recorder test.mp4` always works, here below the output of the command:

```
npx @arcsine/win-info
npx: installed 1 in 0.57s
{
  "title": "vscode.yml - dev-setup - Visual Studio Code",
  "id": 75497473,
  "owner": {
    "name": "Code",
    "processId": 126527
  },
  "screens": [
    {
      "index": 4,
      "width": 1920,
      "height": 1080,
      "x": 0,
      "y": 0,
      "scale": {
        "x": 1,
        "y": 1
      }
    }
  ],
  "bounds": {
    "x": 48,
    "y": 64,
    "width": 1872,
    "height": 1016
  }
}
```

```
npx @arcsine/screen-recorder test.mp4
npx: installed 6 in 2.795s
/usr/bin/ffmpeg -threads 4 -video_size 1872x1016 -f x11grab -i :0+48,64 -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[x11grab @ 0x55e9ab972900] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0+48,64':
  Duration: N/A, start:
1637847203.634630, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1872x1016, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0x55e9ab98ba40] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x55e9ab980940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55e9ab980940] profile High 4:4:4 Predictive, level 4.0, 4:4:4 8-bit
[libx264 @ 0x55e9ab980940] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=6 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj444p(pc), 1872x1016, q=-1--1, 29.97 fps, 30k tbn, 29.97 tbc
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   17 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
frame=   32 fps= 32 q=0.0 size=    1024kB time=00:00:00.40 bitrate=20949.8kbits/s speed=0.399x
frame=   48 fps= 31 q=0.0 size=    1024kB time=00:00:00.93 bitrate=8978.9kbits/s speed=0.608x
frame=   63 fps= 31 q=0.0 size=    1280kB time=00:00:01.43 bitrate=7308.4kbits/s speed=0.704x
frame=   78 fps= 31 q=0.0 size=    1280kB time=00:00:01.93 bitrate=5418.4kbits/s speed=0.763x
frame=   93 fps= 30 q=0.0 size=    1280kB time=00:00:02.43 bitrate=4305.0kbits/s speed=0.796x
frame=  109 fps= 30 q=0.0 size=    1536kB time=00:00:02.96 bitrate=4237.3kbits/s speed=0.826x
frame=  125 fps= 30 q=0.0 size=    1536kB time=00:00:03.50 bitrate=3591.6kbits/s speed=0.853x
frame=  140 fps= 30 q=0.0 size=    1536kB time=00:00:04.00 bitrate=3142.7kbits/s speed=0.869x
Done
frame=  149 fps= 30 q=-1.0 Lsize=    1862kB time=00:00:04.93 bitrate=3089.4kbits/s speed=0.997x    
video:1861kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.075093%
[libx264 @ 0x55e9ab980940] frame I:1     Avg QP: 7.00  size:401889
[libx264 @ 0x55e9ab980940] frame P:148   Avg QP: 2.35  size: 10156
[libx264 @ 0x55e9ab980940] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x55e9ab980940] mb P  I16..4:  1.0%  0.0%  0.0%  P16..4:  5.9%  0.0%  0.0%  0.0%  0.0%    skip:93.1%
[libx264 @ 0x55e9ab980940] coded y,u,v intra: 20.8% 5.9% 5.5% inter: 2.0% 0.9% 0.8%
[libx264 @ 0x55e9ab980940] i16 v,h,dc,p: 82% 17%  1%  0%
[libx264 @ 0x55e9ab980940] kb/s:3065.45
Successfully terminated
```

Note I had chronicler working in the past months.

**Comment by heitor-lassarote** [comment]
> Since you moved back to X11, have you been able to try using the extension again? If the terminal can successfully get win-info and record, the plugin is just calling those same pieces of functionality.

I haven't. The first time I tried it (when I reported the issue) was with X11 as well.

> Note I had chronicler working in the past months.

It's the same for me.

**Comment by arciisine** [comment]
@heitor-lassarote  @ltshb So, nothing has changed with respect to the plugin, so the only culprits would either be environmental, or potentially a VSCode change.  I'm digging into it now, and will update here when I find something.

**Comment by arciisine** [comment]
So, long story short, I was able to replicate the issue and track it down to an electron change.  The extension should be publishing now, and after you update, it should be working.

**Comment by heitor-lassarote** [comment]
Thank you! I just tried the new version and it works.

**Comment by ltshb** [comment]
I updated and tried again, it works again like a charm 👍🏼 . Thanks a lot.
