### ISSUE TITLE
Getting error on start

### ISSUE THREAD

**Issue by jljorden** [arciisine/vscode-chronicler#31]
I get an error when I start recording that says Invalid exit status 1. When I try to run npx @arcsine/win-info I get this:

Unexpected token W in JSON at position 19:
{
    "title": "C:\WINDOWS\system32\cmd.exe ",
    "id": 4655364,
    "owner": {
        "name": "WindowsTerminal.exe",
        "processId": 8776,
        "path": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe"
    },
    "screens": [
        {
          "x": 0,
          "y": 0,
          "width": 2194,
          "height": 1186,
          "index": 0,
          "scale": {
            "x": 1.75,
            "y": 1.75
          }
        } ],
    "bounds": {
        "x": 45,
        "y": 52,
        "width": 1140,
        "height": 638
    }
}

C:\Users\1322919\AppData\Local\npm-cache\_npx\7bdea5cc73c9c05d\node_modules\@arcsine\win-info\index.js:14
        throw new Error('Error parsing data');
        ^

Error: Error parsing data
    at parseJSON (C:\Users\1322919\AppData\Local\npm-cache\_npx\7bdea5cc73c9c05d\node_modules\@arcsine\win-info\index.js:14:15)
    at getActiveSync (C:\Users\1322919\AppData\Local\npm-cache\_npx\7bdea5cc73c9c05d\node_modules\@arcsine\win-info\index.js:55:16)
    at Object.<anonymous> (C:\Users\1322919\AppData\Local\npm-cache\_npx\7bdea5cc73c9c05d\node_modules\@arcsine\win-info\bin\win-info.js:8:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by jljorden** [comment]
Fixed that error, now I get this:
{
  "title": "Windows Terminal",
  "id": 1049918,
  "owner": {
    "name": "WindowsTerminal.exe",
    "processId": 27968,
    "path": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe"
  },
  "screens": [
    {
      "x": 0,
      "y": 0,
      "width": 2194,
      "height": 1186,
      "index": 0,
      "scale": {
        "x": 1.75,
        "y": 1.75
      }
    }
  ],
  "bounds": {
    "x": 788,
    "y": 229,
    "width": 1140,
    "height": 665
  }
}

**Comment by jljorden** [comment]
When I run screen recorder I get this:>
c:\projects\ffmpeg\bin\ffmpeg.exe -f dshow -list_devices true -i dummy
Invalid exit status: 1
c:\projects\ffmpeg\bin\ffmpeg.exe -threads 4 -video_size 1996x1164 -offset_x 1378 -offset_y 400 -f gdigrab -i desktop -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version N-105336-g7247a6fed8-20220121 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.498_5075e1f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220121
libavutil      57. 18.100 / 57. 18.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.100 /  8. 26.100
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
[gdigrab @ 0000020d08de3080] Capturing whole desktop as 1996x1164x32 at (1378,400)
[gdigrab @ 0000020d08de3080] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1642808050.950980, bitrate: 2228195 kb/s
Stream #0:0: Video: bmp, bgra, 1996x1164, 2228195 kb/s, 29.97 fps, 1000k tbr, 1000k tbn
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d08e3d4c0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d08ea2b80] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0de55380] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0df01040] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0df0e000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0dfa9040] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0dfc6b80] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0dfd69c0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000020d08e2b040] [swscaler @ 0000020d0dff3c40] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0000020d0762d840] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0000020d0762d840] profile High 4:4:4 Predictive, level 5.0, 4:4:4, 8-bit
[libx264 @ 0000020d0762d840] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=6 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf59.17.101
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj444p(pc, progressive), 1996x1164, q=2-31, 29.97 fps, 30k tbn
    Metadata:
      encoder         : Lavc59.20.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A
frame=   19 fps=0.0 q=0.0 size=    2304kB time=00:00:00.16 bitrate=113112.6kbits/s dup=7 drop=0 speed=0.308x
frame=   36 fps= 33 q=0.0 size=    3584kB time=00:00:00.73 bitrate=39995.2kbits/s dup=13 drop=0 speed=0.671x
frame=   52 fps= 32 q=0.0 size=    4352kB time=00:00:01.26 bitrate=28117.4kbits/s dup=18 drop=0 speed=0.774x
frame=   67 fps= 31 q=0.0 size=    4608kB time=00:00:01.76 bitrate=21345.7kbits/s dup=23 drop=0 speed=0.827x
frame=   84 fps= 31 q=0.0 size=    6144kB time=00:00:02.33 bitrate=21549.0kbits/s dup=29 drop=0 speed=0.869x
frame=  100 fps= 31 q=0.0 size=    6912kB time=00:00:02.86 bitrate=19732.4kbits/s dup=34 drop=0 speed=0.885x
frame=  115 fps= 31 q=0.0 size=    7424kB time=00:00:03.37 bitrate=18046.5kbits/s dup=38 drop=0 speed=0.899x
frame=  131 fps= 31 q=0.0 size=    7680kB time=00:00:03.90 bitrate=16115.8kbits/s dup=43 drop=0 speed=0.915x
frame=  147 fps= 31 q=0.0 size=    7936kB time=00:00:04.43 bitrate=14649.6kbits/s dup=48 drop=0 speed=0.924x
Done
[q] command received. Exiting.
frame=  149 fps= 30 q=-1.0 Lsize=    8142kB time=00:00:04.93 bitrate=13507.1kbits/s dup=49 drop=0 speed=   1x
video:8141kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.018810%
[libx264 @ 0000020d0762d840] frame I:1     Avg QP: 7.00  size:1156653
[libx264 @ 0000020d0762d840] frame P:148   Avg QP: 3.06  size: 48506
[libx264 @ 0000020d0762d840] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000020d0762d840] mb P  I16..4:  2.5%  0.0%  0.0%  P16..4: 14.1%  0.0%  0.0%  0.0%  0.0%    skip:83.5%
[libx264 @ 0000020d0762d840] coded y,u,v intra: 21.2% 23.3% 23.4% inter: 4.5% 4.0% 4.0%
[libx264 @ 0000020d0762d840] i16 v,h,dc,p: 81% 16%  1%  1%
[libx264 @ 0000020d0762d840] kb/s:13413.06
Successfully terminated

**Comment by jljorden** [comment]
Got it working. I just had to remove the FFMpeg Binary Location setting and start recording, then let Chronicler download ffmpeg on its own. Thanks.
